# Generated by Django 6.0.4 on 2026-05-02 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.CharField(max_length=20, unique=True, verbose_name='Driver ID')),
                ('home_terminal', models.CharField(max_length=100, verbose_name='Home Terminal')),
                ('truck_license', models.CharField(max_length=20, verbose_name='Truck License Plate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
        migrations.CreateModel(
            name='LogDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('driver_number', models.CharField(max_length=20, verbose_name='Driver ID')),
                ('initials', models.CharField(max_length=10, verbose_name='Initials')),
                ('signature', models.CharField(max_length=100, verbose_name='Signature')),
                ('co_driver', models.CharField(default='N/A', max_length=100, verbose_name='Co-driver')),
                ('home_terminal', models.CharField(max_length=100, verbose_name='Home Terminal')),
                ('truck_license', models.CharField(max_length=20, verbose_name='Truck License')),
                ('trailer_1', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Trailer 1')),
                ('trailer_2', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Trailer 2')),
                ('trailer_3', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Trailer 3')),
                ('trailer_4', models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Trailer 4')),
                ('shipper', models.CharField(max_length=100, verbose_name='Shipper')),
                ('commodity', models.CharField(max_length=100, verbose_name='Commodity')),
                ('load_id_1', models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Load ID 1')),
                ('load_id_2', models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Load ID 2')),
                ('load_id_3', models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Load ID 3')),
                ('load_id_4', models.CharField(blank=True, default='N/A', max_length=50, verbose_name='Load ID 4')),
                ('total_driving_hours', models.FloatField(default=0, verbose_name='Total Driving Hours')),
                ('total_on_duty_hours', models.FloatField(default=0, verbose_name='Total On-Duty Hours')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_days', to='logs.driver')),
            ],
            options={
                'verbose_name': 'Work Day',
                'verbose_name_plural': 'Work Days',
                'unique_together': {('driver', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SB', 'Sleeper Berth'), ('D', 'Driving'), ('ON', 'On Duty (Not Driving)')], max_length=3, verbose_name='Status')),
                ('location_city', models.CharField(max_length=100, verbose_name='City')),
                ('location_state', models.CharField(max_length=2, verbose_name='State')),
                ('remarks_extra', models.TextField(blank=True, verbose_name='Additional Remarks')),
                ('log_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='logs.logday')),
            ],
            options={
                'verbose_name': 'Activity Segment',
                'verbose_name_plural': 'Activity Segments',
                'ordering': ['start_time'],
            },
        ),
    ]
