# Generated by Django 6.0.4 on 2026-05-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='uses_70hour_8day',
            field=models.BooleanField(default=True, help_text='True=70h/8d, False=60h/7d'),
        ),
    ]
